# CircleCI configuration file

version: 2.1

jobs:
  install-test:
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout
      - run: ruby --version
      - run: gem install rspec
      - run: rspec --version
      - run: rspec

workflows:
  my-workflow:
    jobs:
      - install-test
# VS Code Extension Version: 1.5.1
